# Generated by Django 5.0.2 on 2024-02-19 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='the tag name', max_length=64, unique=True)),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='the Django auth group for this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='any tags associated with this plan', related_name='tag_plans', to='subscription.plantag'),
        ),
    ]
