# Generated by Django 5.0.2 on 2024-02-19 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_plantag_plan_group_alter_plan_id_plan_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='group',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='PlanTag',
        ),
    ]
